language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
    fast_finish: true
    include:
     - php: 7.0
       env: SYMFONY_VERSION=^3.3
     - php: 7.0
       env: COMPOSER_FLAGS="--prefer-lowest"
     - php: 7.1
       env:
        - SYMFONY_VERSION=^3.4
        - DEPENDENCIES=beta
     - php: 7.2
       env: DEPENDENCIES=beta
     - php: nightly
       env: COMPOSER_FLAGS="--ignore-platform-reqs"
    allow_failures:
     - php: nightly

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

before_script:
  - composer update --no-interaction --no-progress $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit -v --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

#deploy:
#    provider: script
#    script: docs/deploy.sh
#    on:
#        branch: master
