language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
    fast_finish: true
    include:
     - php: 7.0
       env: SYMFONY_VERSION=^3.3
     - php: 7.0
       env: COMPOSER_FLAGS="--prefer-lowest"
     - php: 7.1
     - php: 7.2
     - php: 7.2
       env: DEPENDENCIES=beta
    allow_failures:
     - php: 7.2
     - php: nightly

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

before_script:
  - curl --version
  - composer self-update
  - composer update --no-interaction --no-progress $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit -v --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
