services:
    _defaults:
        autowire: true
        autoconfigure: true

    Omines\DataTablesBundle\:
        resource: '../../{Twig}/*'

    # Register default adapters via autoconfig/autowire
    Omines\DataTablesBundle\Adapter\ArrayAdapter: ~
    Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter: ~

    Omines\DataTablesBundle\DataTableFactory:
        arguments: ['%datatables.settings%', '%datatables.options%']
        public: true

