services:
    _defaults:
        autowire: true
        autoconfigure: true

    Omines\DataTablesBundle\:
        resource: '../../{Adapter,Twig}/*'

    Omines\DataTablesBundle\DataTableFactory:
        arguments: ['%datatables.settings%', '%datatables.options%']
#        calls:
#            - ['setDoctrine', ['@?doctrine']]
        public: true

#    Omines\DataTablesBundle\Twig\DataTablesExtension: ~
