services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Register default adapters via autoconfig/autowire
    Omines\DataTablesBundle\Adapter\ArrayAdapter: ~
    Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter: ~

    Omines\DataTablesBundle\DataTableFactory:
        arguments: ['%datatables.settings%', '%datatables.options%']
        public: true

    Omines\DataTablesBundle\Twig\DataTablesExtension: ~
