services:
    _defaults:
        autowire: true
        autoconfigure: true

    Omines\DataTablesBundle\DataTableFactory:
        arguments: ['%datatables.settings%', '%datatables.options%']
        public: true

    Omines\DataTablesBundle\Twig\DataTablesExtension: ~
