services:
    Omines\DataTablesBundle\DataTableFactory:
        arguments: [null, '%datatables.settings%', '%datatables.options%']

    Omines\DataTablesBundle\Twig\DataTablesExtension:
        arguments: ['@translator']
        tags: [ { name: 'twig.extension' } ]
