services:
    Omines\DatatablesBundle\DatatableFactory:
        arguments: ['%datatables.settings%', '%datatables.options%']

    Omines\DatatablesBundle\Twig\DatatablesExtension:
        arguments: ['@translator']
        tags: [ { name: 'twig.extension' } ]
